### ISSUE TITLE
ArcGIS Pro 3.3.2 Toolbar not functioning

### ISSUE THREAD

**Issue by headart** [lewistrotter/ArcDEA#14]
Great tool thank you. I've just installed it on Pro 3.3.2 and the toolbar isn't launching the functions. Is there a debug menu to see what errors it might be throwing?

![image](https://github.com/user-attachments/assets/9a4de9b7-9d1a-407d-8e23-c13f7b900630)

Directly loading in the toolbox still works.

**Comment by lewistrotter** [comment]
Thanks @headart 

No debug I'm afraid. I haven't had a look at this tool for awhile, so probably needs a good revisit. I should have some time in a week, might go back in and clean up - have been meaning to for awhile. Keep an eye on it.

**Comment by lewistrotter** [comment]
The plugin has now been updated to support Pro 3.3+ and .NET8.
Works on my Pro 3.4 ver. Thanks!

**Comment by headart** [comment]
Thanks for updating that. I seem to be having the same issues still with the update. Would you be able to let me know what version of .NET you are running or if there are any other issues that might be causing it?

**Comment by lewistrotter** [comment]
Strange - the latest Arc SDK needs .NET 8 or above. I believe 3.3. introduced this.
I am running on Pro 3.4, perhaps try latest Pro version if not. Also, try uninstalling the plugin, retsrarting Pro to clear the cache, then install again.
I'll try it on a laptop later and see how it goes.
Thanks.

**Comment by lewistrotter** [comment]
Thanks @headart 
I have tried this now on 3.3 and it no longer works - you will need 3.4 of above due to their .NET 8 update.
Let me know if you have any issues with 3.4.

**Comment by headart** [comment]
I'm still coming up with the same issue as initial but I found esri's diagnostic monitoring tool which flagged the following error:

![image](https://github.com/user-attachments/assets/60cb2af0-1832-48d2-8542-22e4daa9cedd)

I also noticed that the Addin is listing outdated details in the Add-in Manager:
![image](https://github.com/user-attachments/assets/a9378c22-0ed2-4793-8f55-b53fc44973ed)

**Comment by lewistrotter** [comment]
Well, that issue would explain why your buttons are greyed out. It can't seem to find one of the SDK buttons (technically a gallery type). This is certainly in the project during compilation and is being found in my installs.
This could possibly be an issue with your ArcGIS Pro assembly cache, where an older version of the plugin isn't properly being removed when you install the new plugin.

Can you uninstall the plugin through ArcGIS Pro UI, then go to the cache e.g. C:/Users/<NAME>/AppData/Local/ESRI/ArcGISPro/AssemblyCache/
And delete the plugin manually there. Then, launch ArcGIS Pro once and then immediately close it to force reset the cache, then install the plugin.

The above method has helped me reset addin cache issues before, such as "stuck" libraries.

If the above doesn't work I'm not sure what is wrong, as I cannot replicate your issue on my end. The outdated info on the plugin will be fixed but it won't cause any issues, it's just cosmetic.
